INSERT INTO Team(id,name) VALUES(1,'Reason Gaming');
INSERT INTO Team(id,name) VALUES(2,'The Last Resort');
INSERT INTO Team(id,name) VALUES(3,'nerdRage.tf2');
INSERT INTO Team(id,name) VALUES(4,'Hello Kitteh Ninjas!');
INSERT INTO Team(id,name) VALUES(5,'top5rocket');
INSERT INTO Team(id,name) VALUES(6,'Twenty-Seven');
INSERT INTO Team(id,name) VALUES(7,'MenaceToSociety');
INSERT INTO Team(id,name) VALUES(8,'Kids Next Door');
INSERT INTO Team(id,name) VALUES(9,'LEGO Rock Raiders');
INSERT INTO Team(id,name) VALUES(10,'Quadacious & The Fozars');
INSERT INTO Team(id,name) VALUES(11,'froyotech');
INSERT INTO Team(id,name) VALUES(12,'Ascent');
INSERT INTO Team(id,name) VALUES(13,'Street Hoops eSports');
INSERT INTO Team(id,name) VALUES(14,'Getawhale Fanclub');
INSERT INTO Team(id,name) VALUES(15,'Meat Market');
INSERT INTO Team(id,name) VALUES(16,'FAT Gaming');
INSERT INTO Team(id,name) VALUES(17,'-bird noises-');
INSERT INTO Team(id,name) VALUES(18,'6cuties');
INSERT INTO Team(id,name) VALUES(19,'Back to the Lab Again');
