INSERT INTO Class(name) VALUES('scout');
INSERT INTO Class(name) VALUES('pyro');
INSERT INTO Class(name) VALUES('soldier');
INSERT INTO Class(name) VALUES('demoman');
INSERT INTO Class(name) VALUES('engineer');
INSERT INTO Class(name) VALUES('heavy');
INSERT INTO Class(name) VALUES('medic');
INSERT INTO Class(name) VALUES('sniper');
INSERT INTO Class(name) VALUES('spy');
